apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "clicker-presale.fullname" . }}-ingress
  labels:
    {{- include "clicker-presale.labels" . | nindent 4 }}
spec:
  rules:
    - host: {{- if .Values.HOST_NAME_PROD }} {{ .Values.HOST_NAME_PROD }}
          {{- else }} {{ .Values.HOST_NAME }}
          {{- end }}
      http:
        paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              name: {{ include "clicker-presale.fullname" . }}
              port:
                number: {{ .Values.service.port }}
